### ISSUE TITLE
Could not load

### ISSUE THREAD

**Issue by oguh43** [axelrindle/Broadcaster-Plugin#19]
`[17:26:53] [Server thread/ERROR]: Could not load 'plugins/Broadcaster-2.2.0.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: PocketKnife
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:221) [server.jar:git-Bukkit-8160e29]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:349) [server.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:197) [server.jar:git-Bukkit-8160e29]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:762) [server.jar:git-Bukkit-8160e29]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]`
I can provide the full startup log if needed :)

**Comment by axelrindle** [comment]
You have to install an additional plugin as a dependency: [PocketKnife](https://github.com/axelrindle/PocketKnife/releases/latest)

**Comment by oguh43** [comment]
Thanks :)
