### ISSUE TITLE
Error occurred while enabling Broadcaster v2.3.1 (Is it up to date?) java.lang.LinkageError

### ISSUE THREAD

**Issue by TechnicJelle** [axelrindle/Broadcaster-Plugin#25]
**Version information**
| Component | Version |
| ---- | ---- |
| Plugin | `Broadcaster-2.3.1.jar` |
| PocketKnife | `PocketKnife-2.0.0.jar` |
| Bukkit/Spigot | `git-Paper-780 (MC: 1.16.5)` |

**Bug description**
On startup, Broadcaster crashes and shuts itself down again.
```[04:17:48] [Server thread/INFO]: [Broadcaster] Enabling Broadcaster v2.3.1
[04:17:48] [Server thread/INFO]: [Broadcaster] Startup...
[04:17:48] [Server thread/INFO]: [Broadcaster] Loading configuration...
[04:17:48] [Server thread/INFO]: [Broadcaster] Creating new config file 'config' at /var/games/minecraft/servers/gen3/plugins/Broadcaster/config.yml
[04:17:48] [Server thread/INFO]: [Broadcaster] Creating new config file 'messages' at /var/games/minecraft/servers/gen3/plugins/Broadcaster/messages.yml
[04:17:48] [Server thread/INFO]: [Broadcaster] Created example file at /var/games/minecraft/servers/gen3/plugins/Broadcaster/json/visit-github.json.
[04:17:48] [Server thread/INFO]: [Broadcaster] Loading localization...
[04:17:48] [Server thread/INFO]: [Broadcaster] Creating new config file 'localization' at /var/games/minecraft/servers/gen3/plugins/Broadcaster/localization.yml
[04:17:48] [Server thread/INFO]: [Broadcaster] Creating new config file 'lang/en' at /var/games/minecraft/servers/gen3/plugins/Broadcaster/lang/en.yml
[04:17:48] [Server thread/INFO]: [Broadcaster] Creating new config file 'lang/de' at /var/games/minecraft/servers/gen3/plugins/Broadcaster/lang/de.yml
[04:17:48] [Server thread/INFO]: [Broadcaster] Initializing main functionality...
[04:17:48] [Server thread/INFO]: [Broadcaster] Loaded 6 messages.
[04:17:49] [Server thread/ERROR]: Error occurred while enabling Broadcaster v2.3.1 (Is it up to date?)
java.lang.LinkageError: loader constraint violation: when resolving method 'void de.axelrindle.pocketknife.PocketInventory.setItem$default(de.axelrindle.pocketknife.PocketInventory, int, org.bukkit.inventory.ItemStack, kotlin.jvm.functions.Function1, int, java.lang.Object)' the class loader org.bukkit.plugin.java.PluginClassLoader @5ddfcd0c of the current class, de/axelrindle/broadcaster/command/StatusCommand, and the class loader org.bukkit.plugin.java.PluginClassLoader @73a1874d for the method's defining class, de/axelrindle/pocketknife/PocketInventory, have different Class objects for the type kotlin/jvm/functions/Function1 used in the signature (de.axelrindle.broadcaster.command.StatusCommand is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @5ddfcd0c, parent loader 'app'; de.axelrindle.pocketknife.PocketInventory is in unnamed module of loader org.bukkit.plugin.java.PluginClassLoader @73a1874d, parent loader 'app')
at de.axelrindle.broadcaster.command.StatusCommand.<init>(StatusCommand.kt:31) ~[?:?]
at de.axelrindle.broadcaster.command.BrcCommand.<init>(BrcCommand.kt:23) ~[?:?]
at de.axelrindle.broadcaster.Broadcaster.onEnable(Broadcaster.kt:75) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-780]
at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:594) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1069) ~[patched_1.16.5.jar:git-Paper-780]
at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-780]
at java.lang.Thread.run(Thread.java:831) [?:?]
[04:17:49] [Server thread/INFO]: [Broadcaster] Disabling Broadcaster v2.3.1
[04:17:49] [Server thread/INFO]: [Broadcaster] Shutdown complete.
```

**Additional context**
This was on a completely clean reinstall of both PocketKnife and Broadcaster.

**Comment by axelrindle** [comment]
Hm, this looks very weird. The origin seems to be the `StatusCommand` class.

1. I need you to specify the exact implementation and version of Java you're running the server with (Paper prints that at the very start of the logs). Alternatively you can attach the entire server log file.
2. Also, is that a one-time error or does it occur on every startup?

**Comment by TechnicJelle** [comment]
```
~$ java --version
openjdk 16.0.1 2021-04-20
OpenJDK Runtime Environment (build 16.0.1+9-24)
OpenJDK 64-Bit Server VM (build 16.0.1+9-24, mixed mode, sharing)
```

```
~$ uname -a
Linux 4.19.0-17-amd64 #1 SMP Debian 4.19.194-1 (2021-06-10) x86_64 GNU/Linux
```

This happens on every startup..

**Comment by axelrindle** [comment]
Thank you. I will try to reproduce this error using `OpenJDK 16.0.1+9-24`.

**Comment by axelrindle** [comment]
I could reproduce the exact same stacktrace. I will try to figure out what causes this issue and whether there is a temporary workaround. I will keep you updated.

Still this is weird, because I can't remember having such issues when releasing this version.

**Comment by TechnicJelle** [comment]
Thanks for the effort! Here's to hoping it'll be an easy error to solve...

I also think it's weird, because I'd been using the exact same version of the plugin on my server for a while now, and that has been working fine. It only started misbehaving when I moved it from a Windows host to a Linux host and updated Paper (paper-1.16.4-401 --> paper-1.16.5-782) and some other plugins.

**Comment by axelrindle** [comment]
Could you try use that Paper `1.16.4-401` and see if it works again? This could be a temporary workaround then.

**Comment by TechnicJelle** [comment]
It doesn't work. I've only got JDK 16 installed on this server and when I try to run it, it tells me `Unsupported Java detected (60.0). Only up to Java 15 is supported.`

**Comment by axelrindle** [comment]
Hello again. Please try [this snapshot build](https://github.com/axelrindle/Broadcaster-Plugin/files/6858423/Broadcaster-2.4.0-SNAPSHOT.zip) on your server to see if the error still occurs (unzip it beforehand :wink:).

**Comment by TechnicJelle** [comment]
```
[22:15:24] [Server thread/INFO]: [Broadcaster] Enabling Broadcaster v2.4.0
[22:15:24] [Server thread/INFO]: [Broadcaster] Startup...
[22:15:24] [Server thread/INFO]: [Broadcaster] Loading configuration...
[22:15:24] [Server thread/INFO]: [Broadcaster] Loading localization...
[22:15:24] [Server thread/INFO]: [Broadcaster] Creating new config file 'localization' at ./server/plugins/PocketKnife/localization.yml
[22:15:24] [Server thread/INFO]: [Broadcaster] Initializing main functionality...
[22:15:25] [Server thread/INFO]: [Broadcaster] Loaded 6 messages.
[22:15:25] [Server thread/INFO]: [Broadcaster] Connected with VaultAPI.
[22:15:25] [Server thread/INFO]: [Broadcaster] Done! v2.4.0
[22:16:32] [Server thread/INFO]: [Info] > Thanks for using Broadcaster! ???
[22:17:32] [Server thread/INFO]: [Info] > Supports colors and placeholders! ???
[22:18:32] [Server thread/INFO]: [Info] > Ideas? Suggestion? Visit the project page on BukkitDev and write it in the comments! ???
[22:19:32] [Server thread/INFO]: [Info] >                  Centered messages.                         
[22:20:32] [Server thread/INFO]: [Info] > Now also supporting PlaceholderAPI now: TPS => %server_tps%
[22:21:32] [Server thread/INFO]: [Info] > Visit the Github page
[22:22:32] [Server thread/INFO]: [Info] > Thanks for using Broadcaster! ???
[22:23:32] [Server thread/INFO]: [Info] > Supports colors and placeholders! ???
[22:24:32] [Server thread/INFO]: [Info] > Ideas? Suggestion? Visit the project page on BukkitDev and write it in the comments! ???
```

Sure looks like it's fixed, alright!
Awesome!! Thank you very much!

**Comment by axelrindle** [comment]
Sounds great 😁
I will probably release v2.4.0 by the end of this week.

Please reopen this issue if similar issues start occuring again.
